---
abstract: 'turns baubles into trinkets'
author:
  - 'José Eduardo Perotta de Almeida <eduardo@web2solutions.com.br>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300009, CPAN::Meta::Converter version 2.120530'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DHTMLX-Connector
requires:
  JSON: 0
  Locale::Currency::Format: 0
  XML::Mini::Document: 0
  strict: 0
  warnings: 0
version: 0.001
